name: dart_sm
description: sm2,sm3,sm4 crypto for dart
version: 0.2.0
homepage: https://github.com/kuresaru/dart_sm.git

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  convert: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
